### ISSUE TITLE
Slow run time.

### ISSUE THREAD

**Issue by 1T57H3F0X** [1T57H3F0X/loki#1]
Benchmarking showed that it was taking up to _16s_ on some systems to run.

![image](https://user-images.githubusercontent.com/120978468/220782635-81ddbba0-1b82-49f0-9ec4-8def7b83bee3.png)

**Comment by 1T57H3F0X** [comment]
Resolved in commit [#7cc41d9](https://github.com/1T57H3F0X/loki/commit/7cc41d9aa3a38f8b940fc8883352dcc2d843de8b) which added threading.

Benchmarking can now be enabled by uncommenting the relevant lines in `loki.py`.

![image](https://user-images.githubusercontent.com/120978468/220783130-163d9dc3-268d-4ead-bc36-4179f77f32d3.png)

**Comment by marvhus** [comment]
To optimize the run time, try using a compiled language.

**Comment by marvhus** [comment]
> Benchmarking showed that it was taking up to _16s_ on some systems to run.
> 
> ![image](https://user-images.githubusercontent.com/120978468/220782635-81ddbba0-1b82-49f0-9ec4-8def7b83bee3.png)

typo, it's 0.16s or 160ms

**Comment by 1T57H3F0X** [comment]
> > Benchmarking showed that it was taking up to _16s_ on some systems to run.
> > ![image](https://user-images.githubusercontent.com/120978468/220782635-81ddbba0-1b82-49f0-9ec4-8def7b83bee3.png)
> 
> typo, it's 0.16s or 160ms

Updated to reflect typo correction.
